### PR TITLE
fix: fix nested `$set` objects not being restored correctly

### LINKED ISSUE #28: Conflicting parent/child updates when auto-rollbacking nested properties
Source PR: https://github.com/360Learning/platform/pull/76361

## Issue

When we have a Data Migration setting a nested property:
```ts
export function buildMigration() {
    return new MongoBulkDataMigration<Company>({
        db: globalThis._mongoClient.db(),
        id: SCRIPT_TITLE,
        collectionName: "attempts",
        projection: { "contextKey.data": 1 },
        query: { _id: { $in: ATTEMPTS_TO_FIX } },
        update: { $set: { "contextKey.data": {} } }
    });
}
```

The auto-rollback fails with a `MongoBulkWriteError: Updating the path 'contextKey.data' would create a conflict at 'contextKey.data'`. 

It comes from [the way we compute the rollback queries](https://github.com/360Learning/mongo-bulk-data-migration/blob/5bb274f59a9956143da9bffc615f6f7d52370a96/src/lib/computeRollbackQuery.ts#L85). In our case, the rollback will try to do something like that:
```ts
{
  $set: { "contextKey.data": {...} }, // restore the parent to its original value
  $unset: { "contextKey.data.enrollmentId": 1 } // unset all fields that are in the backup but not in the $set
}
```

These are conflicting operations for Mongo Bulk, hence the thrown error. 

## Workaround for users 

Modifying the update operation to update the parent field instead of the child does the trick:
```ts
export function buildMigration() {
    return new MongoBulkDataMigration<Company>({
        db: globalThis._mongoClient.db(),
        id: SCRIPT_TITLE,
        collectionName: "attempts",
        projection: { "contextKey.data": 1 },
        query: { _id: { $in: ATTEMPTS_TO_FIX } },
        update: [
            {
                $set: {
                    contextKey: {
                        type: "$contextKey.type",
                        _id: "$contextKey._id",
                        data: {}
                    }
                }
            }
        ]
    });
}
```

This way, the auto-rollback operation will just re-update the whole parent field, instead of also trying to unset the child property.

### PR DESCRIPTION
**Pull request by hugop95**
- Fixes #28

## Description

A `$set: { "contextKey.data": {} }` query fails when the input data is `{ contextKey: { data: { key: 1 } } }` because the rollback query results in

```ts
{
  "$set": {
    "contextKey.data.key": 1
  },
  "$unset": {
    "contextKey.data": 1
  }
}
```  

## The fix

When checking a backup key to restore when computing the rollback `$set`, the idea is to check if this flattened key  is included in the input `$set`.

In the example above, the backup would be

```ts
{
  "_id": "XXX",
  "contextKey": {
    "data": {
      "key": 1
    }
  }
}
```

The flattened backup key examined would be `contextKey.data.key`, which is "included" in `contextKey.data` present in the input `$set`.

When that happens, instead of setting `"contextKey.data.key": 1` in the rollback `$set`, we instead set `"contextKey.data": { key: 1 }` (and keep populating that object for next keys if needed).

---

The rollback `$unset` is automatically updated in that case and is now empty.

## Changes

- Fix the bug
- [BONUS] Prevent setting `_id` in rollback `$set`.

### CODE REVIEW

**Comment by hugop95** [comment]
cc @arnaudframmery @JulienAmoros FYI

File: src/lib/computeRollbackQuery.ts [hunk 1]
```diff
@@ -111,6 +111,17 @@ function computeRollbackSet(
...
       }
 
+      const setPropertyKeyStartsWith = setPropertiesDuringUpdate.find(
+        (setProperty) => key.startsWith(`${setProperty}.`),
+      );
+      if (setPropertyKeyStartsWith) {
+        rollbackSet[setPropertyKeyStartsWith] =
+          rollbackSet[setPropertyKeyStartsWith] ?? {};
+        const keyToSet = key.slice(setPropertyKeyStartsWith.length + 1);
+        rollbackSet[setPropertyKeyStartsWith][keyToSet] = value;
```
Comment (pp0rtal) [inline src/lib/computeRollbackQuery.ts]: @hugop95 [suggestion] Possibility to do it in a single assignment, matter of taste only :)
```suggestion
        const keyToSet = key.slice(setPropertyKeyStartsWith.length + 1);
        rollbackSet[setPropertyKeyStartsWith] = {
          ...(rollbackSet[setPropertyKeyStartsWith] ?? {}),
          [keyToSet]: value
        }
```

**Review by pp0rtal — APPROVED** [review]
@hugop95 Thank you for fixing this!
Long time this lib was not updated on npm 😃

File: src/lib/computeRollbackQuery.ts (hunk 1 above)
Comment (hugop95) [reply src/lib/computeRollbackQuery.ts]: @pp0rtal 👍

[`fc893f7` (this PR)](https://github.com/360Learning/mongo-bulk-data-migration/pull/29/commits/fc893f74b1f4b31630b8e309f3ca32452d0be216)

**Comment by hugop95** [comment]
@pp0rtal Thank you for the review, I'll let you merge when you want 👍
