### PR TITLE
fix(#17): handles array elements having objects

### LINKED ISSUE #17: [Regression] Arrays having objects not restored
PR #15 introduced this untested case.

I can't find a way to phrase that correctly, but let's give an example:

Migration:
```ts
{
    update: { $set: { array: [] } },
}
```

Source document:

```ts
{
  array: [
    {
      nested: [
        "nestedValue"
      ]
    }
  ]
}
```

Rollback will give:
```
Updating the path 'array' would create a conflict at 'array'
MongoBulkWriteError: Updating the path 'array' would create a conflict at 'array'
```

because rollback query is

```json
{
  "$set": {
    "_id": "671fc94bf125d6ac18ecb470",
    "array.0.nested": [
      "nestedValue"
    ]
  },
  "$unset": {
    "array": 1
  }
}
```

### PR DESCRIPTION
**Pull request by hugop95**
Fixes #17.

### Changes 

- We are going back to what we were doing pre #15, except that on top of checking first.

```ts
const parentKeyToFullyRestore = setPropertiesDuringUpdate.find(
        (userSet) => key.startsWith(`${userSet}.`),
      );
      if (parentKeyToFullyRestore) {
        // ...
      }
```
I added `&& parentKeyToFullyRestore in backup` as well.

- Adds a test to cover this case.

### CODE REVIEW

File: src/lib/computeRollbackQuery.ts [hunk 1]
```diff
@@ -24,6 +24,14 @@ function computeRollbackSet(
 
   return Object.entries(flattenBackupDocument).reduce(
     (rollbackSet, [key, value]) => {
+      const parentKeyToFullyRestore = setPropertiesDuringUpdate.find(
+        (userSet) => key.startsWith(`${userSet}.`),
+      );
+      if (parentKeyToFullyRestore && parentKeyToFullyRestore in backup) {
```
Comment (pp0rtal) [inline src/lib/computeRollbackQuery.ts:30]: @hugop95 You mean `&& parentKeyToFullyRestore in backup` was the right fix for https://github.com/360Learning/mongo-bulk-data-migration/pull/15
Good usage of `in` here

**Review by pp0rtal — COMMENTED** [review]
Trusting you here. I let you check if it fixes your uses cases everywhere.
If so we will bump the patch tomorrow.

File: src/lib/computeRollbackQuery.ts (hunk 1 above)
Comment (hugop95) [reply src/lib/computeRollbackQuery.ts:30]: @pp0rtal I think it is. But I don't know if we cover all cases. If all checks runs successfully, I think it's safe for now. But I wonder if we are not missing another case.

Comment (pp0rtal) [reply src/lib/computeRollbackQuery.ts:30]: @hugop95 Thanks to enforced `doRollbackAndAssertForInitialState` it's safe for those who use it at least.
For anything too much core-releated (auto rollback) next time I'll do a `-rc` version to batch those kind of tricky updates.

**Comment by hugop95** [comment]
@pp0rtal I'll let you update the changelog to your liking (it's an actually an excuse because I'm too tired to find one 🫣) and merge when you want. All of my tests ran successfully, so I think we should be okay.

**Review by pp0rtal — APPROVED** [review]
@hugop95 Thank you
I pushed 1.4.5 on npm
